config/routes.rb
Rails.application.routes.draw do
  get 'cpc/_cpc'
  get 'cpc/index'
  get 'cpc/edit'
  get 'cpc/show'
  get 'cpc/create'
  get 'sogou_ideas/edit'
  get 'sogou_ideas/index'
  get 'sogou_ideas/new'
  get 'sogou_ideas/show'
  get 'sogou_ideas/_sogou_idea'
  get 'sogou_groups/edit'
  get 'sogou_groups/index'
  get 'sogou_groups/new'
  get 'sogou_groups/show'
  get 'sogou_plans/edit'
  get 'sogou_plans/index'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/_form'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/index'
  get 'sogou_plans/edit'
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.superadmin_role? } do
  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :campaigns
  resources :accounts
  resources :adgroups
  resources :keywords

  resources :sogou_plans
  resources :sogou_groups
  resources :sogou_ideas
  resources :cpcs
  devise_for :users

  scope "/superadmin" do
    resources :users
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  # 360's actions 

  get 'accounts/:id/retrieve_campaigns' => 'accounts#retrieve_campaigns', as: :accounts_retrieve_campaigns
  get 'campaigns/:id/retrieve_adgroups' => 'campaigns#retrieve_adgroups', as: :campaigns_retrieve_adgroups
  get 'adgroups/:id/retrieve_keywords' => 'adgroups#retrieve_keywords', as: :adgroup_retrieve_keywords
  get 'accounts/:id/delete_campaigns' => 'accounts#delete_campaigns', as: :accounts_delete_campaigns
  get 'campaigns/:id/delete_adgroups' => 'campaigns#delete_adgroups', as: :campaigns_delete_adgroups
  get 'adgroups/:id/delete_keywords' => 'adgroups#delete_keywords', as: :adgroup_delete_keywords
  get 'superadmin/:id/make_superadmin' => 'users#make_superadmin', as: :make_superadmin

  # sogou's actions

  get 'accounts/:id/retrieve_plans' => 'accounts#sogou_retrieve_plans', as: :accounts_retrieve_plans
  get 'accounts/:id/delete_plans' => 'accounts#delete_plans', as: :accounts_delete_plans
  get 'sogou_plans/:id/retrieve_groups' => 'sogou_plans#sogou_retrieve_groups', as: :sogou_retrieve_groups
  get 'sogou_plans/:id/delete_groups' => 'sogou_plans#sogou_delete_groups', as: :sogou_delete_groups
  get 'sogou_groups/:id/retrieve_ideas' => 'sogou_groups#sogou_retrieve_ideas', as: :sogou_retrieve_ideas
  get 'sogou_groups/:id/delete_ideas' => 'sogou_groups#sogou_delete_ideas', as: :sogou_delete_ideas
  get 'sogou_groups/:id/retrieve_cpcs' => 'sogou_groups#sogou_retrieve_cpcs', as: :sogou_retrieve_cpcs
  get 'sogou_groups/:id/delete_cpcs' => 'sogou_groups#sogou_delete_cpcs', as: :sogou_delete_cpcs
end

app/models/sogou_group.rb
class SogouGroup < ApplicationRecord
  belongs_to :sogou_plan
      #   t.text :negative_words
      # t.text :exact_negative_words
  serialize :negative_words, Array
  serialize :exact_negative_words, Array
  has_many :sogou_ideas, dependent: :destroy
  has_many :cpcs, dependent: :destroy
end

app/controllers/sogou_groups_controller.rb
class SogouGroupsController < ApplicationController
  before_action :find_sogou_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_sogou_group, only: [:show, :edit, :update, :destroy]
  def new
    @sogou_group = SogouGroup.new
  end

  def create
    @sogou_group = SogouGroup.new(sogou_group_params)
  end

  def sogou_retrieve_cpcs

    @group = SogouGroup.find(params[:id])
    @account = @group.sogou_plan.account
    @username = @account.username
    @password = @account.password
    @apitoken = @account.apitoken

    @group_id_array = sogou_retrieve_group_ids(@username, @password, @apitoken)


    @user = sogou_api(@username,@password,@apitoken,"CpcService")

    # retrieve response to API call, convert to hash

    @update_status = @user.call(:get_cpc_id_by_cpc_grp_id, message: {cpcGrpIds: @group_id_array, getTemp: 0})
    
    @stathash = @update_status.body.to_hash

    # retrieve the ideas from the hash

    @cpcs = @stathash[:get_cpc_id_by_cpc_grp_id_response][:cpc_grp_cpc_ids]

    @cpcs.each do |cpc|
      
      if cpc.keys.count >= 2
        
        @status = @user.call(:get_cpc_by_cpc_id, message: { cpcIds: cpc[:cpc_ids] })
        cpc_to_s=@status.body.to_hash
        
        cpc_to_s = cpc_to_s[:get_cpc_by_cpc_id_response]
        cpc_to_s.delete(:"@xmlns:ns2")
        cpc_to_s.delete(:"@xmlns:ns3")

        
            #         @update_status = @user.call(:get_cpc_id_by_cpc_grp_id, message: {cpcGrpIds: @group_id_array, getTemp: 0})
    # cpc_id = @update_status.body.to_hash
    # cpc_id = cpc_id[:get_cpc_id_by_cpc_grp_id_response][:cpc_grp_cpc_ids]

    # cpcs = {}

    # cpc_id.each do |cpc|
    #   if cpc.keys.count >= 2
    #     @status = @user.call(:get_cpc_by_cpc_id, message: { cpcIds: cpc[:cpc_ids] })
    #     cpcs[cpc[:cpc_grp_id]]=@status.body.to_hash
    #   end
    # end


      for j in 0..cpc_to_s[:cpc_types].length
        cpc_tos = cpc_to_s[:cpc_types][j]
        byebug
        if cpc_tos.has_key?(:mobile_visit_url)
          cpc_tos.delete(:mobile_visit_url)
        end

        cpc_to_su = Cpc.new(cpc_tos)
        @group.cpcs.push(cpc_to_su)

      end
      end
    end

    # @cpcs.each do |cpc|
    #   @idea = idea
    #   group_id = @idea[:cpc_grp_id]
    #   if group_id = @group.cpc_grp_id
    #     for i in 0..@idea[:cpc_idea_types].length
    #       ideax = @idea[:cpc_idea_types][i]
    #       sgi = SogouIdea.create(ideax)
    #       @group.sogou_ideas.push(sgi)
    #   end
    #   end 
    # end
    @account.save
    redirect_to @group
    flash[:success] = "CPCs for #{@account.channel}-#{@account.username} retrieved."


  end

  def sogou_retrieve_ideas

  	@group = SogouGroup.find(params[:id])
    @account = @group.sogou_plan.account
    @username = @account.username
    @password = @account.password
    @apitoken = @account.apitoken
    @group_id_array = sogou_retrieve_group_ids(@username, @password, @apitoken)


    @user = sogou_api(@username,@password,@apitoken,"CpcIdeaService")

    # retrieve response to API call, convert to hash

    @update_status = @user.call(:get_cpc_idea_by_cpc_grp_id, message: { cpcGrpIds: @group_id_array })
    
    @stathash = @update_status.body.to_hash

    # retrieve the ideas from the hash

    @ideas = @stathash[:get_cpc_idea_by_cpc_grp_id_response][:cpc_grp_ideas]
	  @ideas.each do |idea|
      @idea = idea
      group_id = @idea[:cpc_grp_id]
      if group_id = @group.cpc_grp_id
      	for i in 0..@idea[:cpc_idea_types].length
      		ideax = @idea[:cpc_idea_types][i]
      		sgi = SogouIdea.create(ideax)
      		@group.sogou_ideas.push(sgi)
  		end
  	  end 
    end
    @account.save
    redirect_to @group
    flash[:success] = "Ideas for #{@account.channel}-#{@account.username} retrieved."

  end

  def sogou_delete_ideas
    # operates under the assumption that user has already created an account.
    @sogou_group = SogouGroup.find(params[:id])

    if @sogou_group.sogou_ideas.count > 0
      @sogou_group.sogou_ideas.destroy_all
      flash[:success] = "Your ideas have been deleted."
    else
      flash[:success] = "No ideas to delete."
    end
    redirect_to @sogou_group
  end

  def sogou_delete_cpcs
    # operates under the assumption that user has already created an account.
    @sogou_group = SogouGroup.find(params[:id])

    if @sogou_group.cpcs.count > 0
      @sogou_group.cpcs.destroy_all
      flash[:success] = "Your cpcs have been deleted."
    else
      flash[:success] = "No cpcs to delete."
    end
    redirect_to @sogou_group
  end
   def destroy
    session[:return_to] ||= request.referer
    @sogou_group.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private 
  	def find_sogou_group
      @sogou_group = SogouGroup.find(params[:id])
    end

    def owned_sogou_group
      unless current_user.id == @sogou_group.sogou_plan.account.user_id
      redirect_to root_path
      end
    end
     def sogou_group_params
      params.require(:sogou_group).permit(:cpc_grp_id, :cpc_plan_id, :cpc_grp_name, 
      	:max_price,:negative_words, :exact_negative_words,:pause, :status, :opt)
    end

end

app/helpers/sogou_groups_helper.rb
module SogouGroupsHelper
end

app/views/sogou_groups/_sogou_group.html.erb
<tbody>
  <td>    <% if (params[:page]).to_i == 0 %>
    <%= index = (sogou_group_counter + 1) + (((params[:page]).to_i) * Kaminari.paginate_array(user_campaigns).limit_value ) %>
    <% else %>
    <%= index = (sogou_group_counter + 1) + (((params[:page]).to_i - 1) * Kaminari.paginate_array(user_campaigns).limit_value ) %></td>
    <% end %></td>
  <td><%= sogou_group.cpc_grp_name %></td>
  <td><%= sogou_group.cpc_grp_id %></td>
  <td><%= sogou_group.max_price %></td>
  <td><%= link_to "#{sogou_group.sogou_ideas.count} Ideas", sogou_group, class: "btn bg-info"  %></td>
  <td><%= link_to "#{sogou_group.cpcs.count} CPCs", sogou_group, class: "btn bg-info"  %></td>
  <td><%= link_to 'Delete Group', sogou_group, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-button", :class => "btn bg-info button" %></td>
        <% else %></td>
</tbody>

app/views/sogou_groups/edit.html.erb
<h1>SogouGroups#edit</h1>
<p>Find me in app/views/sogou_groups/edit.html.erb</p>

app/views/sogou_groups/index.html.erb
<h1>SogouGroups#index</h1>
<p>Find me in app/views/sogou_groups/index.html.erb</p>

app/views/sogou_groups/new.html.erb
<h1>SogouGroups#new</h1>
<p>Find me in app/views/sogou_groups/new.html.erb</p>

app/views/sogou_groups/show.html.erb
<h4>
<%= link_to 'All accounts',  accounts_path %>
<span class="glyphicon glyphicon-chevron-right"></span>
<%= link_to "#{@sogou_group.sogou_plan.account.channel} - #{@sogou_group.sogou_plan.account.username}", @sogou_group.sogou_plan.account%>
<span class="glyphicon glyphicon-chevron-right"></span>
<%="#{@sogou_group.cpc_grp_name}"%>
</h4>

<h2>Sogou Ideas</h2>
<p><%= pluralize(@sogou_group.sogou_ideas.count, "Ideas") %> associated with this Group</p>

  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve Ideas', sogou_retrieve_ideas_path(:id => @sogou_group.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete Ideas', sogou_delete_ideas_path(:id => @sogou_group.id), :method => "get", :id => "delete-button", :class => "btn bg-info button"%>

    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Sogou Group name</th>
          <th>Sogou Group id</th>
          </tr>

        <% if @sogou_group.sogou_ideas %>
        <%= paginate Kaminari.paginate_array(@sogou_group.sogou_ideas).page(params[:page]).per(25) %>
        <%= render Kaminari.paginate_array(@sogou_group.sogou_ideas).page(params[:page]).per(25) %>
        <% end %>
      </thead>

      </table>
    </div>


<h2>Sogou CPCs</h2>
<p><%= pluralize(@sogou_group.cpcs.count, "CPCs") %> associated with this Group</p>

  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve Cpcs', sogou_retrieve_cpcs_path(:id => @sogou_group.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete Ideas', sogou_delete_cpcs_path(:id => @sogou_group.id), :method => "get", :id => "delete-button", :class => "btn bg-info button"%>

    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Sogou CPC name</th>
          <th>Sogou CPC id</th>
          </tr>

        <% if @sogou_group.cpcs %>
        <%= paginate Kaminari.paginate_array(@sogou_group.cpcs).page(params[:page]).per(25) %>
        <%= render Kaminari.paginate_array(@sogou_group.cpcs).page(params[:page]).per(25) %>
        <% end %>
      </thead>

      </table>
    </div>

    <div id="footer-javascripts">

    <script type="text/javascript">
      $("button.retrieve-adgroups").on("click", function() {
        window.location = "<%= campaigns_retrieve_adgroups_path(:id => @sogou_group.id) %>"
      })
    </script>

    <script type="text/javascript">
      $("button.delete-adgroups").on("click", function() {
        window.location = "<%= campaigns_delete_adgroups_path(:id => @sogou_group.id) %>"
      })
    </script>
    </div>