config/routes.rb
Rails.application.routes.draw do
  get 'cpc/_cpc'
  get 'cpc/index'
  get 'cpc/edit'
  get 'cpc/show'
  get 'cpc/create'
  get 'sogou_ideas/edit'
  get 'sogou_ideas/index'
  get 'sogou_ideas/new'
  get 'sogou_ideas/show'
  get 'sogou_ideas/_sogou_idea'
  get 'sogou_groups/edit'
  get 'sogou_groups/index'
  get 'sogou_groups/new'
  get 'sogou_groups/show'
  get 'sogou_plans/edit'
  get 'sogou_plans/index'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/_form'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/index'
  get 'sogou_plans/edit'
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.superadmin_role? } do
  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :campaigns
  resources :accounts
  resources :adgroups
  resources :keywords

  resources :sogou_plans
  resources :sogou_groups
  resources :sogou_ideas
  resources :cpcs
  devise_for :users

  scope "/superadmin" do
    resources :users
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  # 360's actions 

  get 'accounts/:id/retrieve_campaigns' => 'accounts#retrieve_campaigns', as: :accounts_retrieve_campaigns
  get 'campaigns/:id/retrieve_adgroups' => 'campaigns#retrieve_adgroups', as: :campaigns_retrieve_adgroups
  get 'adgroups/:id/retrieve_keywords' => 'adgroups#retrieve_keywords', as: :adgroup_retrieve_keywords
  get 'accounts/:id/delete_campaigns' => 'accounts#delete_campaigns', as: :accounts_delete_campaigns
  get 'campaigns/:id/delete_adgroups' => 'campaigns#delete_adgroups', as: :campaigns_delete_adgroups
  get 'adgroups/:id/delete_keywords' => 'adgroups#delete_keywords', as: :adgroup_delete_keywords
  get 'superadmin/:id/make_superadmin' => 'users#make_superadmin', as: :make_superadmin

  # sogou's actions

  get 'accounts/:id/retrieve_plans' => 'accounts#sogou_retrieve_plans', as: :accounts_retrieve_plans
  get 'accounts/:id/delete_plans' => 'accounts#delete_plans', as: :accounts_delete_plans
  get 'sogou_plans/:id/retrieve_groups' => 'sogou_plans#sogou_retrieve_groups', as: :sogou_retrieve_groups
  get 'sogou_plans/:id/delete_groups' => 'sogou_plans#sogou_delete_groups', as: :sogou_delete_groups
  get 'sogou_groups/:id/retrieve_ideas' => 'sogou_groups#sogou_retrieve_ideas', as: :sogou_retrieve_ideas
  get 'sogou_groups/:id/delete_ideas' => 'sogou_groups#sogou_delete_ideas', as: :sogou_delete_ideas
  get 'sogou_groups/:id/retrieve_cpcs' => 'sogou_groups#sogou_retrieve_cpcs', as: :sogou_retrieve_cpcs
  get 'sogou_groups/:id/delete_cpcs' => 'sogou_groups#sogou_delete_cpcs', as: :sogou_delete_cpcs
end

app/models/adgroup.rb
class Adgroup < ApplicationRecord
  belongs_to :campaign
  has_many :keywords, dependent: :destroy
  paginates_per 2
end

app/controllers/adgroups_controller.rb
class AdgroupsController < ApplicationController
  before_action :find_adgroup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_adgroup, only: [:show, :edit, :update, :destroy]

  def retrieve_keywords
    @adgroup = Adgroup.find(params[:id])
    @username = @adgroup.campaign.account.username
    @password = @adgroup.campaign.account.password
    @apitoken = @adgroup.campaign.account.apitoken
    @apisecret = @adgroup.campaign.account.apisecret
    @target = "keywords"
    message = ::ApiCall::DataRetriever.new(reference_element: @adgroup, username: @username, password: @password, apitoken: @apitoken, apisecret: @apisecret, target: @target).call_api
    redirect_to @adgroup
    flash[:success] = message
  end


  def delete_keywords
    # operates under the assumption that user has already created an account.
    @adgroup = Adgroup.find(params[:id])

    if @adgroup.keywords.count > 0
      @adgroup.keywords.destroy_all
      flash[:success] = "Your keywords have been deleted."
    else
      flash[:success] = "No keywords to delete."

    end
    redirect_to @adgroup

  end

  # def index
  # end

  def show

  end

  def new
    @adgroup = Adgroup.new
  end

  def edit
  end

  def create
    @adgroup = Adgroup.new(adgroup_params)

    respond_to do |format|
      if @adgroup.save
        format.html { redirect_to @adgroup, notice: 'Adgroup was successfully created.' }
        format.json { render :show, status: :created, location: @adgroup }
      else
        format.html { render :new }
        format.json { render json: @adgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @adgroup.update(adgroup_params)
        format.html { redirect_to @adgroup, notice: 'Adgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @adgroup }
      else
        format.html { render :edit }
        format.json { render json: @adgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    session[:return_to] ||= request.referer
    @adgroup.destroy
    respond_to do |format|
      format.html {  redirect_to session.delete(:return_to), notice: 'Adgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def find_adgroup
      @adgroup = Adgroup.find(params[:id])
    end

    def owned_adgroup
      unless current_user.id == @adgroup.campaign.account.user_id
      redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adgroup_params
      params.require(:adgroup).permit(:campaign_id, :name)
    end
end

app/helpers/adgroups_helper.rb
module AdgroupsHelper
  end

app/views/adgroups/_adgroup.html.erb
<tbody>
  <td>
  	<% if (params[:page]).to_i == 0 %>
  	<%= index = (adgroup_counter + 1) + (((params[:page]).to_i) * Kaminari.paginate_array(@campaign.adgroups).limit_value ) %>
  	<% else %>
  	<%= index = (adgroup_counter + 1) + (((params[:page]).to_i - 1) * Kaminari.paginate_array(@campaign.adgroups).limit_value ) %></td>
  	<% end %>
  <td><%= adgroup.name %></td>
  <td><%= adgroup.channel_id %></td>

  <td><%= link_to "#{adgroup.keywords.count} Keywords", adgroup, class: "btn bg-info"  %></td>
  <!-- <td><%= link_to 'Edit adgroup', edit_adgroup_path(adgroup) %></td> -->
  <td><%= link_to 'Delete adgroup', adgroup, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-button", :class => "btn bg-info button"  %></td>
</tbody>

app/views/adgroups/_form.html.erb
<%= form_with(model: adgroup, local: true) do |form| %>
<% if adgroup.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(adgroup.errors.count, "error") %>
      prohibited this adgroup from being saved:</h2>

    <ul>
      <% adgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
</div>

<!-- <div class="form-group"> <%= form.label :account_id %> <%= form.select :account_id, ['option1', 'option2'], class: "form-control" %> </div> -->

<div class="form-group">
  <%= form.label :campaign_ID %>
  <%= form.number_field :campaign_id, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit "Submit", class:"btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/adgroups/edit.html.erb
<h1>Editing Adgroup</h1>

<%= render 'form', adgroup: @adgroup %>

<%= link_to 'Show', @adgroup %> |
<%= link_to 'Back', adgroups_path %>

app/views/adgroups/index.html.erb
<h1>Your Adgroups</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Adgroup id</th>
        <th colspan="3"></th>
      </tr>
      <% if user_adgroups %>        
      <%= paginate Kaminari.paginate_array(user_adgroups).page(params[:page]).per(25) %>
      <%= render Kaminari.paginate_array(user_adgroups).page(params[:page]).per(25) %>
    </thead>
  </table>
  
  </div>
  <% else %>
</thead>
</table>
</div>
  <br>
      <div>No adgroup associated with your account</div>
      <% end%>
<br>
    <!-- <% if @campaigns.first %>
      <div>
      <%= link_to 'New Adgroup', new_adgroup_path %>
    <% else %>
      <p>You must first create a campaign in order to create an adgroup.</p>
    <% end %>
    </div> -->

app/views/adgroups/new.html.erb
<h1>New Adgroup</h1>

<%= render 'form', adgroup: @adgroup %>

<%= link_to 'Back', adgroups_path %>

app/views/adgroups/show.html.erb
<h4>
  <%= link_to 'All accounts',  accounts_path %>
  <span class="glyphicon glyphicon-chevron-right"></span>
  <%= link_to "#{@adgroup.campaign.account.channel} - #{@adgroup.campaign.account.username}", @adgroup.campaign.account%>
  <span class="glyphicon glyphicon-chevron-right"></span>
  <%= link_to "#{@adgroup.campaign.name}", @adgroup.campaign%>
  <span class="glyphicon glyphicon-chevron-right"></span>
  <%="#{@adgroup.name}"%>

</h4>

<h2> Keywords</h2>

  <p><%= pluralize(@adgroup.keywords.count, "keywords") %> associated with this adgroup</p>
  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve Keywords', adgroup_retrieve_keywords_path(:id => @adgroup.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete All Keywords', adgroup_delete_keywords_path(:id => @adgroup.id), :method => "get", :id => "delete-button", :class => "btn bg-info float-right button" %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Keyword Title</th>
          <th>Keyword channel id</th>
          </tr>
      <% if @adgroup.keywords %>
      <%= paginate Kaminari.paginate_array(@adgroup.keywords).page(params[:page]).per(25) %>
      <%= render Kaminari.paginate_array(@adgroup.keywords).page(params[:page]).per(25) %>
      <% end %>
      </thead>

      </table>

    </div>