config/routes.rb
Rails.application.routes.draw do
  get 'cpc/_cpc'
  get 'cpc/index'
  get 'cpc/edit'
  get 'cpc/show'
  get 'cpc/create'
  get 'sogou_ideas/edit'
  get 'sogou_ideas/index'
  get 'sogou_ideas/new'
  get 'sogou_ideas/show'
  get 'sogou_ideas/_sogou_idea'
  get 'sogou_groups/edit'
  get 'sogou_groups/index'
  get 'sogou_groups/new'
  get 'sogou_groups/show'
  get 'sogou_plans/edit'
  get 'sogou_plans/index'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/_form'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/index'
  get 'sogou_plans/edit'
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.superadmin_role? } do
  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :campaigns
  resources :accounts
  resources :adgroups
  resources :keywords

  resources :sogou_plans
  resources :sogou_groups
  resources :sogou_ideas
  resources :cpcs
  devise_for :users

  scope "/superadmin" do
    resources :users
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  # 360's actions 

  get 'accounts/:id/retrieve_campaigns' => 'accounts#retrieve_campaigns', as: :accounts_retrieve_campaigns
  get 'campaigns/:id/retrieve_adgroups' => 'campaigns#retrieve_adgroups', as: :campaigns_retrieve_adgroups
  get 'adgroups/:id/retrieve_keywords' => 'adgroups#retrieve_keywords', as: :adgroup_retrieve_keywords
  get 'accounts/:id/delete_campaigns' => 'accounts#delete_campaigns', as: :accounts_delete_campaigns
  get 'campaigns/:id/delete_adgroups' => 'campaigns#delete_adgroups', as: :campaigns_delete_adgroups
  get 'adgroups/:id/delete_keywords' => 'adgroups#delete_keywords', as: :adgroup_delete_keywords
  get 'superadmin/:id/make_superadmin' => 'users#make_superadmin', as: :make_superadmin

  # sogou's actions

  get 'accounts/:id/retrieve_plans' => 'accounts#sogou_retrieve_plans', as: :accounts_retrieve_plans
  get 'accounts/:id/delete_plans' => 'accounts#delete_plans', as: :accounts_delete_plans
  get 'sogou_plans/:id/retrieve_groups' => 'sogou_plans#sogou_retrieve_groups', as: :sogou_retrieve_groups
  get 'sogou_plans/:id/delete_groups' => 'sogou_plans#sogou_delete_groups', as: :sogou_delete_groups
  get 'sogou_groups/:id/retrieve_ideas' => 'sogou_groups#sogou_retrieve_ideas', as: :sogou_retrieve_ideas
  get 'sogou_groups/:id/delete_ideas' => 'sogou_groups#sogou_delete_ideas', as: :sogou_delete_ideas
  get 'sogou_groups/:id/retrieve_cpcs' => 'sogou_groups#sogou_retrieve_cpcs', as: :sogou_retrieve_cpcs
  get 'sogou_groups/:id/delete_cpcs' => 'sogou_groups#sogou_delete_cpcs', as: :sogou_delete_cpcs
end

app/models/sogou_plan.rb
class SogouPlan < ApplicationRecord
	belongs_to :account
	serialize :schedule, Array
	has_many :sogou_groups, dependent: :destroy
end

app/controllers/sogou_plans_controller.rb
class SogouPlansController < ApplicationController
  before_action :find_sogou_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_sogou_plan, only: [:show, :edit, :update, :destroy]
  def new
    @sogou_plan = SogouPlan.new
  end

  def create
    @sogou_plan = SogouPlan.new(sogou_plan_params)
  end

  def destroy
    session[:return_to] ||= request.referer
    @sogou_plan.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sogou_retrieve_groups

    @plan = SogouPlan.find(params[:id])
    @account = @plan.account
    @username = @account.username
    @password = @account.password
    @apitoken = @account.apitoken

    @group_id_array = sogou_retrieve_group_ids(@username, @password, @apitoken)
    
    @group_id_array.each do |g|
      @account.group_id_array.push(g)
    end
    
    @user = sogou_api(@username,@password,@apitoken,"CpcGrpService")

    @update_status = @user.call(:get_cpc_grp_by_cpc_grp_id, message: {cpcGrpIds: @group_id_array})

    @update_status = @update_status.body.to_hash[:get_cpc_grp_by_cpc_grp_id_response][:cpc_grp_types]
   
    @update_status.each do |g|
      if g[:cpc_plan_id] == @plan.cpc_plan_id
        sg = SogouGroup.create(g)
        @plan.sogou_groups.push(sg)

      end
      
    end
    redirect_to @plan
    flash[:success] = "Grps for #{@account.channel}-#{@account.username} retrieved."

  end



  def sogou_delete_groups
    # operates under the assumption that user has already created an account.
    @sogou_plan = SogouPlan.find(params[:id])

    if @sogou_plan.sogou_groups.count > 0
      @sogou_plan.sogou_groups.destroy_all
      flash[:success] = "Your groups have been deleted."
    else
      flash[:success] = "No groups to delete."
    end
    redirect_to @sogou_plan

  end



  private 
    def find_sogou_plan
      @sogou_plan = SogouPlan.find(params[:id])
    end

    def owned_sogou_plan
      unless current_user.id == @sogou_plan.account.user_id
      redirect_to root_path
      end
    end
     def sogou_plan_params
      params.require(:sogou_plan).permit(:cpc_plan_id, :cpc_plan_name, :budget, :schedule,:pause,:join_union,:negative_words, :impressions, :clicks)
    end
end

app/helpers/sogou_plans_helper.rb
module SogouPlansHelper
end

app/views/sogou_plans/_form.html.erb
<%= form_with(model: sogouplan, local: true) do |form| %>
<% if sogouplan.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(sogouplan.errors.count, "error") %>
      prohibited this sogouplan from being saved:</h2>

    <ul>
      <% sogouplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :budget %>
  <%= form.text_field :budget, class: "form-control" %>
</div>

<!-- <div class="form-group"> <%= form.label :account_id %> <%= form.select :account_id, ['option1', 'option2'], class: "form-control" %> </div> -->

<div class="form-group">
  <%= form.label :account_ID %>
  <%= form.number_field :account_id, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit "Submit", class:"btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/sogou_plans/_sogou_plan.html.erb
<tbody>
  <td>    <% if (params[:page]).to_i == 0 %>
    <%= index = (sogou_plan_counter + 1) + (((params[:page]).to_i) * Kaminari.paginate_array(user_campaigns).limit_value ) %>
    <% else %>
    <%= index = (sogou_plan_counter + 1) + (((params[:page]).to_i - 1) * Kaminari.paginate_array(user_campaigns).limit_value ) %></td>
    <% end %></td>
  <td><%= sogou_plan.cpc_plan_name %></td>
  <td><%= sogou_plan.cpc_plan_id %></td>
  <td><%= sogou_plan.budget %></td>

  <td><%= link_to "#{sogou_plan.sogou_groups.count} Groups", sogou_plan, class: "btn bg-info"  %></td>

  <td><%= link_to 'Delete Plan', sogou_plan, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-button", :class => "btn bg-info button" %></td>
        <% else %></td>
</tbody>

app/views/sogou_plans/edit.html.erb
<h1>SogouPlans#edit</h1>
<p>Find me in app/views/sogou_plans/edit.html.erb</p>

app/views/sogou_plans/index.html.erb
<h1>SogouPlans#index</h1>
<p>Find me in app/views/sogou_plans/index.html.erb</p>

app/views/sogou_plans/new.html.erb
<h1>SogouPlans#new</h1>
<p>Find me in app/views/sogou_plans/new.html.erb</p>

app/views/sogou_plans/show.html.erb
<h4>
<%= link_to 'All accounts',  accounts_path %>
<span class="glyphicon glyphicon-chevron-right"></span>
<%= link_to "#{@sogou_plan.account.channel} - #{@sogou_plan.account.username}", @sogou_plan.account%>
<span class="glyphicon glyphicon-chevron-right"></span>
<%="#{@sogou_plan.cpc_plan_name}"%>
</h4>

<h2>Sogou Groups</h2>
<p><%= pluralize(@sogou_plan.sogou_groups.count, "Groups") %> associated with this campaign</p>

  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve Groups', sogou_retrieve_groups_path(:id => @sogou_plan.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete Groups', sogou_delete_groups_path(:id => @sogou_plan.id), :method => "get", :id => "delete-button", :class => "btn bg-info button"%>

    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Sogou Group name</th>
          <th>Sogou Group id</th>
          </tr>

        <% if @sogou_plan.sogou_groups %>
        <%= paginate Kaminari.paginate_array(@sogou_plan.sogou_groups).page(params[:page]).per(25) %>
        <%= render Kaminari.paginate_array(@sogou_plan.sogou_groups).page(params[:page]).per(25) %>
        <% end %>
      </thead>

      </table>
    </div>

    <div id="footer-javascripts">

    <script type="text/javascript">
      $("button.retrieve-adgroups").on("click", function() {
        window.location = "<%= campaigns_retrieve_adgroups_path(:id => @sogou_plan.id) %>"
      })
    </script>

    <script type="text/javascript">
      $("button.delete-adgroups").on("click", function() {
        window.location = "<%= campaigns_delete_adgroups_path(:id => @sogou_plan.id) %>"
      })
    </script>
    </div>