config/routes.rb
Rails.application.routes.draw do
  get 'cpc/_cpc'
  get 'cpc/index'
  get 'cpc/edit'
  get 'cpc/show'
  get 'cpc/create'
  get 'sogou_ideas/edit'
  get 'sogou_ideas/index'
  get 'sogou_ideas/new'
  get 'sogou_ideas/show'
  get 'sogou_ideas/_sogou_idea'
  get 'sogou_groups/edit'
  get 'sogou_groups/index'
  get 'sogou_groups/new'
  get 'sogou_groups/show'
  get 'sogou_plans/edit'
  get 'sogou_plans/index'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/_form'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/index'
  get 'sogou_plans/edit'
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.superadmin_role? } do
  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :campaigns
  resources :accounts
  resources :adgroups
  resources :keywords

  resources :sogou_plans
  resources :sogou_groups
  resources :sogou_ideas
  resources :cpcs
  devise_for :users

  scope "/superadmin" do
    resources :users
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  # 360's actions 

  get 'accounts/:id/retrieve_campaigns' => 'accounts#retrieve_campaigns', as: :accounts_retrieve_campaigns
  get 'campaigns/:id/retrieve_adgroups' => 'campaigns#retrieve_adgroups', as: :campaigns_retrieve_adgroups
  get 'adgroups/:id/retrieve_keywords' => 'adgroups#retrieve_keywords', as: :adgroup_retrieve_keywords
  get 'accounts/:id/delete_campaigns' => 'accounts#delete_campaigns', as: :accounts_delete_campaigns
  get 'campaigns/:id/delete_adgroups' => 'campaigns#delete_adgroups', as: :campaigns_delete_adgroups
  get 'adgroups/:id/delete_keywords' => 'adgroups#delete_keywords', as: :adgroup_delete_keywords
  get 'superadmin/:id/make_superadmin' => 'users#make_superadmin', as: :make_superadmin

  # sogou's actions

  get 'accounts/:id/retrieve_plans' => 'accounts#sogou_retrieve_plans', as: :accounts_retrieve_plans
  get 'accounts/:id/delete_plans' => 'accounts#delete_plans', as: :accounts_delete_plans
  get 'sogou_plans/:id/retrieve_groups' => 'sogou_plans#sogou_retrieve_groups', as: :sogou_retrieve_groups
  get 'sogou_plans/:id/delete_groups' => 'sogou_plans#sogou_delete_groups', as: :sogou_delete_groups
  get 'sogou_groups/:id/retrieve_ideas' => 'sogou_groups#sogou_retrieve_ideas', as: :sogou_retrieve_ideas
  get 'sogou_groups/:id/delete_ideas' => 'sogou_groups#sogou_delete_ideas', as: :sogou_delete_ideas
  get 'sogou_groups/:id/retrieve_cpcs' => 'sogou_groups#sogou_retrieve_cpcs', as: :sogou_retrieve_cpcs
  get 'sogou_groups/:id/delete_cpcs' => 'sogou_groups#sogou_delete_cpcs', as: :sogou_delete_cpcs
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :campaigns, :dependent => :destroy
  has_many :sogou_plans, :dependent => :destroy
  serialize :group_id_array, Array
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :find_account, only: [:show, :edit, :update, :destroy, :retrieve_campaigns]
  before_action :owned_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def retrieve_campaigns
    @username = @account.username
    @password = @account.password
    @apitoken = @account.apitoken
    @apisecret = @account.apisecret
    @response = threesixty_login(@username, @password, @apitoken, @apisecret)
    @accesstoken = @response["account_clientLogin_response"]["accessToken"]
    @retrieved_campaigns_ids = threesixty_campaignids(@apitoken, @accesstoken)
    @account_campaigns = @account.campaigns
    RetrieveCampaigns.perform_later(@account.id)
    if @account.campaigns.count < 1
    @message = "Campaigns for #{@account.channel}-#{@account.username} are being retrieved. Check the account page shortly."
    else
      @account_campaign_ids = []
      @account.campaigns.each do |a| @account_campaign_ids.push(a.channel_id)
      end
      if
        @retrieved_campaigns_ids.sort == @account_campaign_ids.sort
        @message = "Campaigns for #{@account.channel}-#{@account.username} are already up to date."
      else
        @message = "Campaigns for #{@account.channel}-#{@account.username} are being updated. Check the campaign page shortly."
      end
    end
    redirect_to accounts_path
    flash[:success] = @message
    # flash[:success] = message
  end

  def sogou_retrieve_plans

    @account = Account.find(params[:id])
    @username = @account.username
    @password = @account.password
    @apitoken = @account.apitoken

    @plan_ids = sogou_retrieve_plan_ids(@username,@password,@apitoken)

    @user = sogou_api(@username, @password, @apitoken, "CpcPlanService")

    @update_status = @user.call(:get_all_cpc_plan)

    @plans = []
    @plans = @update_status.body.to_hash[:get_all_cpc_plan_response][:cpc_plan_types]

    @plans.each do |p|

      sg = SogouPlan.create(p)

      @account.sogou_plans.push(sg)
      
    end
    @account.save
    redirect_to @account
    flash[:success] = "Plans for #{@account.channel}-#{@account.username} have been successfully retrieved."
  end


  def delete_campaigns
    # operates under the assumption that user has already created an account.
    @account = Account.find(params[:id])
    @current_campaigns = @account.campaigns

    if @account.campaigns.count > 0
      @account.campaigns.destroy_all
      flash[:success] = "Your campaigns have been deleted."
    else
      flash[:success] = "No campaigns to delete."
    end
    redirect_to @account

  end

  def delete_plans
    # operates under the assumption that user has already created an account.
    @account = Account.find(params[:id])

    if @account.sogou_plans.count > 0
      @account.sogou_plans.destroy_all
      flash[:success] = "Your plans have been deleted."
    else
      flash[:success] = "No plans to delete."
    end
    redirect_to @account

  end

  def index
    @user = current_user
    @accounts = @user.accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.build
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = current_user.accounts.build(account_params)
    # @account = Account.new(account_params)
    @success = false

    @login = nil

    if @account.channel == "Sogou"
      # do stuff with sogou
      @login = sogou_login(@account.email,@account.password,@account.apitoken)
      @err = ""
      @messg = ""
      respond_to do |format|
        if @login[:res_header][:desc] == "success"
          # create the account and save to database
          @account.save
          format.html { redirect_to accounts_path, notice: @login[:res_header][:desc].to_s + ': Account was successfully created.' }
          format.json { render :show, status: :created, location: @account }
        else
          @account = Account.new(account_params)

          if @login[:res_header].key?(:failures)
            code = @login[:res_header][:failures][:code]

            if code == "6"
              @err = "Error Code 6: Invalid Username. Original message: "
            elsif code == "8"
              @err = "Error Code 8: Invalid Password. Original message: "
            elsif code == "10"
              @err = "Error Code 10: Invalid Token. Original message: "
            else 
              @err = "Unknown Error took place. Original message: "
            end

            @err += @login[:res_header][:failures][:message]
          end
          
          # 6用户名无效
          # username failure


          # {:res_header=>{:desc=>"failure", :failures=>{:code=>"8", :message=>"密码无效"
          # password failure

          # :failures=>{:code=>"10", :message=>"token无效", 


          flash[:notice]= @err
          format.html { render new_account_path }
          format.json { render json: @login.to_s, status: :unprocessable_entity }


        end 
        # will include english translations of failures

      end 

    else
      # do stuff with 360
      @login = threesixty_login(@account.email,@account.password,@account.apitoken,@account.apisecret)
      @err = ""
      @messg = ""
      respond_to do |format|
        if @login != "ERROR"
          if !@login["account_clientLogin_response"].key?("failures") && @login != "ERROR"
            @account.save
            format.html { redirect_to accounts_path, notice: @login.to_s + 'Account was successfully created.' }
            format.json { render :show, status: :created, location: @account }
          else

            @account = Account.new(account_params)

            if @login["account_clientLogin_response"].key?("failures")
              @err = @login["account_clientLogin_response"]["failures"]["item"]["message"].to_s
            else
              # @err = @login.to_s # this should be "ERROR"
            end

            if @err == "登录失败次数超限；每天登录失败次数限制5次；"
              @messg = "You have exceeded the number of failed login attempts (5). Try again in 24 hours. " + @err
            elsif @err == "登录失败；密码格式有误；"
              @messg = "The password for this account is incorrect. Make sure you are trying to access the correct account. " + @err
            elsif @err == "登录失败；用户名和密码不匹配；"
              @messg = "Unable to log in. Make sure you have entered the correct API tokens. "
            elsif @err == "登录失败；无法获取到用户ID；"
              @messg = "Couldn't find user. Make sure your credentials are correct. "            else
              @messg = "An unknown error occurred. " + @err
            end
            flash[:notice]= @messg
            format.html { render new_account_path }
            format.json { render json: @login.to_s, status: :unprocessable_entity }
          end
        else
            @account = Account.new(account_params)
            @messg = "Unexpected error. Please make sure your API tokens are correct."
            flash[:notice]= @messg
            format.html { render new_account_path }
            format.json { render json: @login.to_s, status: :unprocessable_entity }
      end
    end
  end



  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_account
      @account = Account.find(params[:id])
    end

    def owned_account
      unless current_user.id == @account.user_id
      redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:channel, :username, :email, :password, :apitoken, :apisecret, :user_id)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
  <tbody class="account-fields">
    <td id="align-middle"><%= index = account_counter +1 %></td>
    <td id="align-middle"><%= account.channel %></td>
    <td id="align-middle"><%= account.username %></td>
    <td id="align-middle"><%= account.email %></td>
    <td id="align-middle"><%= account.password %></td>
    <td id="align-middle"><%= account.apitoken %></td>
    <td id="align-middle"><%= account.apisecret %></td>
    <td>
        <% if account.channel == '360' %>
        <%= link_to "#{account.campaigns.count} Campaigns", account, class: "btn bg-info"  %></td>
        <% else %>
        <%= link_to "#{account.sogou_plans.count} Plans", account, class: "btn bg-info"  %>
        <% end %>
    </td>
    <td><%= link_to 'Edit account', edit_account_path(account) %></td>
    <td><%= link_to 'Delete account', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tbody>

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :channel %>
    <%= form.select(:channel, ['360', 'Sogou'], {}, { :class => "form-control" }) %>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :apitoken %>
    <%= form.text_field :apitoken, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :apisecret %>
    <%= form.text_field :apisecret, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class:"btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Your Accounts</h1>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Channel</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Apitoken</th>
      <th>Apisecret</th>
      <th colspan="3"></th>
    </tr>
    <% if current_user.accounts %>
      <%= paginate Kaminari.paginate_array(current_user.accounts).page(params[:page]).per(25) %>
      <%= render Kaminari.paginate_array(current_user.accounts).page(params[:page]).per(25) %>
      <%end%>

  </thead>

</table>
</div>

<br>
<%= link_to 'Add Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h4>
<%= link_to 'All accounts',  accounts_path %>
<span class="glyphicon glyphicon-chevron-right"></span>
<%="#{@account.channel} - #{@account.username}" %>
</h4>
<% if @account.channel == "360" %>
<h2>Campaigns</h2>
  <p><%= pluralize(@account.campaigns.count, "Campaign") %> associated with this account</p>

  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve campaigns', accounts_retrieve_campaigns_path(:id => @account.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete All Campaigns', accounts_delete_campaigns_path(:id => @account.id), :method => "get", :id => "delete-button", :class => "btn bg-info button" %>
    </div>
  </div>


  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Campaign name</th>
          <th>Campaign channel</th>
          <th>Channel id </th>
          </tr>

      </thead>
      <div class="">
        <% if @account.campaigns %>
        <%= paginate Kaminari.paginate_array(@account.campaigns).page(params[:page]).per(25) %>
        <%= render Kaminari.paginate_array(@account.campaigns).page(params[:page]).per(25) %>
        <% end %>
      </div>

      </table>

    </div>

<% else %>

<h2>Plans</h2>
  <p><%= pluralize(@account.sogou_plans.count, "Plans") %> associated with this account</p>

  <div class="row button-container">
    <div class="col-sm-3">
      <%= button_to 'Retrieve Plans', accounts_retrieve_plans_path(:id => @account.id), :method => "get", :id => "retrieve-button", :class => "btn bg-info button"%>
    </div>
    <div class="col-sm-3">
      <%= button_to 'Delete All Plans', accounts_delete_plans_path(:id => @account.id), :method => "get", :id => "delete-button", :class => "btn bg-info button" %>
    </div>
  </div>


  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Plan name</th>
          <th>Plan channel</th>
          <th>Plan id </th>
          </tr>

      </thead>
      <div class="">
        <% if @account.sogou_plans %>
        <%= paginate Kaminari.paginate_array(@account.sogou_plans).page(params[:page]).per(25) %>
        <%= render Kaminari.paginate_array(@account.sogou_plans).page(params[:page]).per(25) %>
        <% end %>
      </div>

      </table>

    </div>

<% end %>